viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
        consumer_topic: !ENV ${PULSAR_CONSUMER_TOPIC}
    pid:
        url: !ENV ${PID_URL}