viaa:
    logging:
        level: DEBUG
app:
    mh_sidecar_version: !ENV ${MH_SIDECAR_VERSION}
    aip_folder: !ENV ${MH_SIP_FOLDER}
    host: !ENV ${HOST}
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
        consumer_topic: !ENV ${MH_SIP_CREATOR_CONSUMER_TOPIC}
        producer_topic: !ENV ${MH_SIP_COMPLEX_PRODUCER_TOPIC}
    pid:
        url: !ENV ${PID_URL}
    storage:
        default_archive_location: !ENV ${DEFAULT_ARCHIVE_LOCATION}
        tape_content_partners: !ENV ${TAPE_CONTENT_PARTNERS}
        disk_content_partners: !ENV ${DISK_CONTENT_PARTNERS}
