viaa:
    logging:
        level: DEBUG
app:
    aip_folder: !ENV ${MH_SIP_FOLDER}
    host: !ENV ${HOST}
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
        consumer_topic: !ENV ${MH_SIP_CREATOR_CONSUMER_TOPIC}
        producer_topic: !ENV ${MH_SIP_COMPLEX_PRODUCER_TOPIC}
    pid:
        url: !ENV ${PID_URL}